'use strict'

// var anchorLinks, dest, anchor
// anchorLinks = document.querySelector('nav').querySelectorAll('a')
//
// for (var i = 0; i < anchorLinks.length; i++) {
// 	anchorLinks[i].addEventListener('click', function () {
// 		anchor = this.getAttribute('href')
// 		dest = document.querySelector(anchor)
// 		window.scroll({ top: dest.offsetTop - 30, behavior: 'smooth' })
// 	})
// }
// map

const SA = document.querySelector('#SA')
const saContent = document.querySelector('.sa-content')
const AE = document.querySelector('#AE')
const aeContent = document.querySelector('.ae-content')
const OM = document.querySelector('#OM')
const omContent = document.querySelector('.om-content')
const YE = document.querySelector('#YE')
const yeContent = document.querySelector('.ye-content')
const IL = document.querySelector('#IL')
const PS = document.querySelector('#PS')
const ilpsContent = document.querySelector('.ilps-content')
const JO = document.querySelector('#JO')
const joContent = document.querySelector('.jo-content')
const EG = document.querySelector('#EG')
const egContent = document.querySelector('.eg-content')
const SY = document.querySelector('#SY')
const syContent = document.querySelector('.sy-content')
const LB = document.querySelector('#LB')
const lbContent = document.querySelector('.lb-content')


// console.log(window.innerWidth)
window.addEventListener('resize', function () {
	if (window.innerWidth < 1200) {
		saContent.style.opacity = '1'
		aeContent.style.opacity = '1'
		omContent.style.opacity = '1'
		yeContent.style.opacity = '1'
		ilpsContent.style.opacity = '1'
		joContent.style.opacity = '1'
		egContent.style.opacity = '1'
		syContent.style.opacity = '1'
		lbContent.style.opacity = '1'
	} else {
		saContent.style.opacity = '0'
		aeContent.style.opacity = '0'
		omContent.style.opacity = '0'
		yeContent.style.opacity = '0'
		ilpsContent.style.opacity = '0'
		joContent.style.opacity = '0'
		egContent.style.opacity = '0'
		syContent.style.opacity = '0'
		lbContent.style.opacity = '0'
	}
})
SA.addEventListener('click', function () {
	saContent.style.transition = '2s'
	aeContent.style.transition = '0s'
  omContent.style.transition = '0s'
	yeContent.style.transition = '0s'
	ilpsContent.style.transition = '0s'
	joContent.style.transition = '0s'
	egContent.style.transition = '0s'
	syContent.style.transition = '0s'
	lbContent.style.transition = '0s'
	saContent.style.opacity = '1'
	aeContent.style.opacity = '0'
	omContent.style.opacity = '0'
	yeContent.style.opacity = '0'
	ilpsContent.style.opacity = '0'
	joContent.style.opacity = '0'
	egContent.style.opacity = '0'
	syContent.style.opacity = '0'
	lbContent.style.opacity = '0'
	SA.style.fill = '#FFCB1B'
	AE.style.fill = 'default'
	OM.style.fill = 'default'
	YE.style.fill = 'default'
	IL.style.fill = 'default'
	PS.style.fill = 'default'
	JO.style.fill = 'default'
	EG.style.fill = 'default'
	SY.style.fill = 'default'
	LB.style.fill = 'default'
})
AE.addEventListener('click', function () {
	saContent.style.transition = '0s'
	aeContent.style.transition = '2s'
  omContent.style.transition = '0s'
	yeContent.style.transition = '0s'
	ilpsContent.style.transition = '0s'
	joContent.style.transition = '0s'
	egContent.style.transition = '0s'
	syContent.style.transition = '0s'
	lbContent.style.transition = '0s'
	saContent.style.opacity = '0'
	aeContent.style.opacity = '1'
	omContent.style.opacity = '0'
	yeContent.style.opacity = '0'
	ilpsContent.style.opacity = '0'
	joContent.style.opacity = '0'
	egContent.style.opacity = '0'
	syContent.style.opacity = '0'
	lbContent.style.opacity = '0'
	SA.style.fill = 'default'
	AE.style.fill = '#FFCB1B'
	OM.style.fill = 'default'
	YE.style.fill = 'default'
	IL.style.fill = 'default'
	PS.style.fill = 'default'
	JO.style.fill = 'default'
	EG.style.fill = 'default'
	SY.style.fill = 'default'
	LB.style.fill = 'default'
})
OM.addEventListener('click', function () {
	saContent.style.transition = '0s'
	aeContent.style.transition = '0s'
	omContent.style.transition = '2s'
	yeContent.style.transition = '0s'
	ilpsContent.style.transition = '0s'
	joContent.style.transition = '0s'
	egContent.style.transition = '0s'
	syContent.style.transition = '0s'
	lbContent.style.transition = '0s'
	saContent.style.opacity = '0'
	aeContent.style.opacity = '0'
	omContent.style.opacity = '1'
	yeContent.style.opacity = '0'
	ilpsContent.style.opacity = '0'
	joContent.style.opacity = '0'
	egContent.style.opacity = '0'
	syContent.style.opacity = '0'
	lbContent.style.opacity = '0'
	SA.style.fill = 'default'
	AE.style.fill = 'default'
	OM.style.fill = '#FFCB1B'
	YE.style.fill = 'default'
	IL.style.fill = 'default'
	PS.style.fill = 'default'
	JO.style.fill = 'default'
	EG.style.fill = 'default'
	SY.style.fill = 'default'
	LB.style.fill = 'default'
})
YE.addEventListener('click', function () {
	saContent.style.transition = '0s'
	aeContent.style.transition = '0s'
	omContent.style.transition = '0s'
	yeContent.style.transition = '2s'
	ilpsContent.style.transition = '0s'
	joContent.style.transition = '0s'
	egContent.style.transition = '0s'
	syContent.style.transition = '0s'
	lbContent.style.transition = '0s'
	saContent.style.opacity = '0'
	aeContent.style.opacity = '0'
	omContent.style.opacity = '0'
	yeContent.style.opacity = '1'
	ilpsContent.style.opacity = '0'
	joContent.style.opacity = '0'
	egContent.style.opacity = '0'
	syContent.style.opacity = '0'
	lbContent.style.opacity = '0'
	SA.style.fill = 'default'
	AE.style.fill = 'default'
	OM.style.fill = 'default'
	YE.style.fill = '#FFCB1B'
	IL.style.fill = 'default'
	PS.style.fill = 'default'
	JO.style.fill = 'default'
	EG.style.fill = 'default'
	SY.style.fill = 'default'
	LB.style.fill = 'default'
})
IL.addEventListener('click', function () {
	saContent.style.transition = '0s'
	aeContent.style.transition = '0s'
	omContent.style.transition = '0s'
	yeContent.style.transition = '0s'
	ilpsContent.style.transition = '2s'
	joContent.style.transition = '0s'
	egContent.style.transition = '0s'
	syContent.style.transition = '0s'
	lbContent.style.transition = '0s'
	saContent.style.opacity = '0'
	aeContent.style.opacity = '0'
	omContent.style.opacity = '0'
	yeContent.style.opacity = '0'
	ilpsContent.style.opacity = '1'
	joContent.style.opacity = '0'
	egContent.style.opacity = '0'
	syContent.style.opacity = '0'
	lbContent.style.opacity = '0'
	SA.style.fill = 'default'
	AE.style.fill = 'default'
	OM.style.fill = 'default'
	YE.style.fill = 'default'
	IL.style.fill = '#FFCB1B'
	PS.style.fill = 'default'
	JO.style.fill = 'default'
	EG.style.fill = 'default'
	SY.style.fill = 'default'
	LB.style.fill = 'default'
})
PS.addEventListener('click', function () {
	saContent.style.transition = '0s'
	aeContent.style.transition = '0s'
	omContent.style.transition = '0s'
	yeContent.style.transition = '0s'
	ilpsContent.style.transition = '2s'
	joContent.style.transition = '0s'
	egContent.style.transition = '0s'
	syContent.style.transition = '0s'
	lbContent.style.transition = '0s'
	saContent.style.opacity = '0'
	aeContent.style.opacity = '0'
	omContent.style.opacity = '0'
	yeContent.style.opacity = '0'
	ilpsContent.style.opacity = '1'
	joContent.style.opacity = '0'
	egContent.style.opacity = '0'
	syContent.style.opacity = '0'
	lbContent.style.opacity = '0'
	SA.style.fill = 'default'
	AE.style.fill = 'default'
	OM.style.fill = 'default'
	YE.style.fill = 'default'
	IL.style.fill = 'default'
	PS.style.fill = '#FFCB1B'
	JO.style.fill = 'default'
	EG.style.fill = 'default'
	SY.style.fill = 'default'
	LB.style.fill = 'default'
})
JO.addEventListener('click', function () {
	saContent.style.transition = '0s'
	aeContent.style.transition = '0s'
	omContent.style.transition = '0s'
	yeContent.style.transition = '0s'
	ilpsContent.style.transition = '0s'
	joContent.style.transition = '2s'
	egContent.style.transition = '0s'
	syContent.style.transition = '0s'
	lbContent.style.transition = '0s'
	saContent.style.opacity = '0'
	aeContent.style.opacity = '0'
	omContent.style.opacity = '0'
	yeContent.style.opacity = '0'
	ilpsContent.style.opacity = '0'
	joContent.style.opacity = '1'
	egContent.style.opacity = '0'
	syContent.style.opacity = '0'
	lbContent.style.opacity = '0'
	SA.style.fill = 'default'
	AE.style.fill = 'default'
	OM.style.fill = 'default'
	YE.style.fill = 'default'
	IL.style.fill = 'default'
	PS.style.fill = 'default'
	JO.style.fill = '#FFCB1B'
	EG.style.fill = 'default'
	SY.style.fill = 'default'
	LB.style.fill = 'default'
})
EG.addEventListener('click', function () {
	saContent.style.transition = '0s'
	aeContent.style.transition = '0s'
	omContent.style.transition = '0s'
	yeContent.style.transition = '0s'
	ilpsContent.style.transition = '0s'
	joContent.style.transition = '0s'
	egContent.style.transition = '2s'
	syContent.style.transition = '0s'
	lbContent.style.transition = '0s'
	saContent.style.opacity = '0'
	aeContent.style.opacity = '0'
	omContent.style.opacity = '0'
	yeContent.style.opacity = '0'
	ilpsContent.style.opacity = '0'
	joContent.style.opacity = '0'
	egContent.style.opacity = '1'
	syContent.style.opacity = '0'
	lbContent.style.opacity = '0'
	SA.style.fill = 'default'
	AE.style.fill = 'default'
	OM.style.fill = 'default'
	YE.style.fill = 'default'
	IL.style.fill = 'default'
	PS.style.fill = 'default'
	JO.style.fill = 'default'
	EG.style.fill = '#FFCB1B'
	SY.style.fill = 'default'
	LB.style.fill = 'default'
})
SY.addEventListener('click', function () {
	saContent.style.transition = '0s'
	aeContent.style.transition = '0s'
	omContent.style.transition = '0s'
	yeContent.style.transition = '0s'
	ilpsContent.style.transition = '0s'
	joContent.style.transition = '0s'
	egContent.style.transition = '0s'
	syContent.style.transition = '2s'
	lbContent.style.transition = '0s'
	saContent.style.opacity = '0'
	aeContent.style.opacity = '0'
	omContent.style.opacity = '0'
	yeContent.style.opacity = '0'
	ilpsContent.style.opacity = '0'
	joContent.style.opacity = '0'
	egContent.style.opacity = '0'
	syContent.style.opacity = '1'
	lbContent.style.opacity = '0'
	SA.style.fill = 'default'
	AE.style.fill = 'default'
	OM.style.fill = 'default'
	YE.style.fill = 'default'
	IL.style.fill = 'default'
	PS.style.fill = 'default'
	JO.style.fill = 'default'
	EG.style.fill = 'default'
	SY.style.fill = '#FFCB1B'
	LB.style.fill = 'default'
})
LB.addEventListener('click', function () {
	saContent.style.transition = '0s'
	aeContent.style.transition = '0s'
	omContent.style.transition = '0s'
	yeContent.style.transition = '0s'
	ilpsContent.style.transition = '0s'
	joContent.style.transition = '0s'
	egContent.style.transition = '0s'
	syContent.style.transition = '0s'
	lbContent.style.transition = '2s'
	saContent.style.opacity = '0'
	aeContent.style.opacity = '0'
	omContent.style.opacity = '0'
	yeContent.style.opacity = '0'
	ilpsContent.style.opacity = '0'
	joContent.style.opacity = '0'
	egContent.style.opacity = '0'
	syContent.style.opacity = '0'
	lbContent.style.opacity = '1'
	SA.style.fill = 'default'
	AE.style.fill = 'default'
	OM.style.fill = 'default'
	YE.style.fill = 'default'
	IL.style.fill = 'default'
	PS.style.fill = 'default'
	JO.style.fill = 'default'
	EG.style.fill = 'default'
	SY.style.fill = 'default'
	LB.style.fill = '#FFCB1B'
})
